/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Maloof
 */
public class A4Q10 extends javax.swing.JFrame {

    /**
     * Creates new form A4Q10
     */
    public A4Q10() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fahrenheitLabel = new javax.swing.JLabel();
        celsiusLabel = new javax.swing.JLabel();
        fahrenheitField = new javax.swing.JTextField();
        celsiusField = new javax.swing.JTextField();
        toCelsiusButton = new javax.swing.JToggleButton();
        toFahrenheitButton = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fahrenheitLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        fahrenheitLabel.setText("Degrees Fahrenheit");

        celsiusLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        celsiusLabel.setText("Degrees Celsius");

        fahrenheitField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fahrenheitFieldActionPerformed(evt);
            }
        });

        toCelsiusButton.setText("F -> C");
        toCelsiusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toCelsiusButtonActionPerformed(evt);
            }
        });

        toFahrenheitButton.setText("C -> F");
        toFahrenheitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toFahrenheitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fahrenheitLabel)
                    .addComponent(celsiusLabel))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(celsiusField, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(fahrenheitField))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(toCelsiusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toFahrenheitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fahrenheitLabel)
                    .addComponent(fahrenheitField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toCelsiusButton))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(celsiusLabel)
                    .addComponent(celsiusField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toFahrenheitButton))
                .addContainerGap(106, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fahrenheitFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fahrenheitFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fahrenheitFieldActionPerformed

    private void toCelsiusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toCelsiusButtonActionPerformed
        String celsiusString = celsiusField.getText();
        String fahrenheitString = fahrenheitField.getText();
        
        // convert strings to doubles
        double fahrenheitNumber = Double.parseDouble(fahrenheitString);
        
        // sets celsius number as converted fahrenheit number
        double celsiusNumber = (((fahrenheitNumber - 32) * 5) / 9);
        
        // rounds to nearest whole number
        celsiusNumber = Math.round(celsiusNumber);
        
        // display answer in resultOutput
        celsiusField.setText("" + celsiusNumber);
    }//GEN-LAST:event_toCelsiusButtonActionPerformed

    private void toFahrenheitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toFahrenheitButtonActionPerformed
        String celsiusString = celsiusField.getText();
        String fahrenheitString = fahrenheitField.getText();
        
        // convert strings to doubles
        double celsiusNumber = Double.parseDouble(celsiusString);
        
        // sets celsius number as converted fahrenheit number
        double fahrenheitNumber = (((celsiusNumber * 9) / 5) + 32);
        
        // rounds to nearest whole number
        fahrenheitNumber = Math.round(fahrenheitNumber);
        
        // display answer in resultOutput
        fahrenheitField.setText("" + fahrenheitNumber);
    }//GEN-LAST:event_toFahrenheitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(A4Q10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(A4Q10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(A4Q10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(A4Q10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new A4Q10().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField celsiusField;
    private javax.swing.JLabel celsiusLabel;
    private javax.swing.JTextField fahrenheitField;
    private javax.swing.JLabel fahrenheitLabel;
    private javax.swing.JToggleButton toCelsiusButton;
    private javax.swing.JToggleButton toFahrenheitButton;
    // End of variables declaration//GEN-END:variables
}
