/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ranam3235
 */
public class A4Q9 extends javax.swing.JFrame {

    /**
     * Creates new form A4Q9
     */
    public A4Q9() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        firstNumberLabel = new javax.swing.JLabel();
        secondNumberLabel = new javax.swing.JLabel();
        resultLabel = new javax.swing.JLabel();
        firstNumberInput = new javax.swing.JTextField();
        secondNumberInput = new javax.swing.JTextField();
        resultOutput = new javax.swing.JTextField();
        addButton = new javax.swing.JToggleButton();
        mulButton = new javax.swing.JToggleButton();
        divButton = new javax.swing.JToggleButton();
        subButton = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        firstNumberLabel.setText("First Number:");

        secondNumberLabel.setText("Second Number:");

        resultLabel.setText("Result:");

        firstNumberInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNumberInputActionPerformed(evt);
            }
        });

        resultOutput.setEditable(false);
        resultOutput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultOutputActionPerformed(evt);
            }
        });

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        mulButton.setText("Mul");
        mulButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mulButtonActionPerformed(evt);
            }
        });

        divButton.setText("Div");
        divButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divButtonActionPerformed(evt);
            }
        });

        subButton.setText("Sub");
        subButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(secondNumberLabel)
                    .addComponent(resultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstNumberLabel))
                .addGap(129, 129, 129)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(firstNumberInput)
                    .addComponent(resultOutput, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                    .addComponent(secondNumberInput))
                .addGap(90, 90, 90))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(addButton)
                .addGap(13, 13, 13)
                .addComponent(subButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mulButton)
                .addGap(18, 18, 18)
                .addComponent(divButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNumberLabel)
                    .addComponent(firstNumberInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(secondNumberLabel)
                    .addComponent(secondNumberInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resultLabel)
                    .addComponent(resultOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(mulButton)
                    .addComponent(divButton)
                    .addComponent(subButton))
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resultOutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultOutputActionPerformed

    }//GEN-LAST:event_resultOutputActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // gather numbers from input fields as strings

        String firstNumberString = firstNumberInput.getText();
        String secondNumberString = secondNumberInput.getText();

        // convert strings to doubles
        double firstNumber = Double.parseDouble(firstNumberString);
        double secondNumber = Double.parseDouble(secondNumberString);

        // add firstNumber and secondNumber
        double addTotal = firstNumber + secondNumber;

        // display answer in resultOutput
        resultOutput.setText("" + addTotal);

    }//GEN-LAST:event_addButtonActionPerformed

    private void firstNumberInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNumberInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNumberInputActionPerformed

    private void mulButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mulButtonActionPerformed
        // gather numbers from input fields as strings

        String firstNumberString = firstNumberInput.getText();
        String secondNumberString = secondNumberInput.getText();

        // convert strings to doubles
        double firstNumber = Double.parseDouble(firstNumberString);
        double secondNumber = Double.parseDouble(secondNumberString);

        // multiply firstNumber and secondNumber
        double mulTotal = firstNumber * secondNumber;

        // display answer in resultOutput
        resultOutput.setText("" + mulTotal);
    }//GEN-LAST:event_mulButtonActionPerformed

    private void subButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subButtonActionPerformed
        // gather numbers from input fields as strings

        String firstNumberString = firstNumberInput.getText();
        String secondNumberString = secondNumberInput.getText();

        // convert strings to doubles
        double firstNumber = Double.parseDouble(firstNumberString);
        double secondNumber = Double.parseDouble(secondNumberString);

        // sub firstNumber and secondNumber
        double subTotal = firstNumber - secondNumber;

        // display answer in resultOutput
        resultOutput.setText("" + subTotal);
    }//GEN-LAST:event_subButtonActionPerformed

    private void divButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divButtonActionPerformed
        // gather numbers from input fields as strings

        String firstNumberString = firstNumberInput.getText();
        String secondNumberString = secondNumberInput.getText();

        // convert strings to doubles
        double firstNumber = Double.parseDouble(firstNumberString);
        double secondNumber = Double.parseDouble(secondNumberString);

        // div firstNumber from secondNumber
        double divTotal = firstNumber / secondNumber;

        // display answer in resultOutput
        resultOutput.setText("" + divTotal);
    }//GEN-LAST:event_divButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(A4Q9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(A4Q9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(A4Q9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(A4Q9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new A4Q9().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton addButton;
    private javax.swing.JToggleButton divButton;
    private javax.swing.JTextField firstNumberInput;
    private javax.swing.JLabel firstNumberLabel;
    private javax.swing.JToggleButton mulButton;
    private javax.swing.JLabel resultLabel;
    private javax.swing.JTextField resultOutput;
    private javax.swing.JTextField secondNumberInput;
    private javax.swing.JLabel secondNumberLabel;
    private javax.swing.JToggleButton subButton;
    // End of variables declaration//GEN-END:variables
}
